name: flutter_example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.0
  charts_flutter: ^0.11.0
  intl: ^0.17.0
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  path_provider: ^2.0.11
  sqflite: ^2.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true